AWSTemplateFormatVersion: "2010-09-09"
Resources:
  JobApplicationsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: JobApplications
      AttributeDefinitions:
        - AttributeName: applicationId
          AttributeType: S
      KeySchema:
        - AttributeName: applicationId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  UserDocumentsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: UserDocuments
      AttributeDefinitions:
        - AttributeName: documentId
          AttributeType: S
      KeySchema:
        - AttributeName: documentId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  NotificationsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: Notifications
      AttributeDefinitions:
        - AttributeName: notificationId
          AttributeType: S
      KeySchema:
        - AttributeName: notificationId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
